### ISSUE TITLE
Continuous Integration for Jupyter Notebook tutorials

### ISSUE THREAD

**Issue by iancze** [MPoL-dev/MPoL#27]
**Is your feature request related to a problem or opportunity? Please describe.**
Most if not all of the core routines of MPoL are currently covered by test suites, which has helped boost the development velocity of the package significantly (there are, of course, ways this could be improved, but at least it's reached a serviceable level).

As we now build out the [tutorials](https://mpol-dev.github.io/MPoL/developer-documentation.html#contributing-tutorials) (based on Jupytext, Jupyter notebook, nbconvert, and nbsphinx), I'm not sure how to properly place them within a continuous integration environment. Some of the tutorial runtimes are substantial (minutes) and (optionally) require more advanced resources (GPUs or multiple cores). Currently, we've made a distinction for two groups

1. `ci-tutorials` which are small enough to be executed within the Github actions environment in a matter of minutes. Following [exoplanet](https://github.com/exoplanet-dev/exoplanet), these are checked in as `*.py` source files and, on Github actions, are converted/executed to `*.ipynb` files using Jupytext and nbsphinx. This works well as a CI strategy, since a failed notebook execution will stop the build. This doesn't catch the case where the notebook fully executes but produces erroneous output, but perhaps this could be addressed with tools like [pytest-notebook](https://pypi.org/project/pytest-notebook/) or even just hidden assert statements. 
2. [`large tutorials`](https://mpol-dev.github.io/MPoL/developer-documentation.html#larger-tutorials-requiring-substantial-computational-resources) which have a longer runtime (> 30 seconds) or would benefit from advanced resources (multiple CPUs or a GPU). Currently, we store the `*.py` source file, convert/execute to `*.ipynb` using Jupytext and a local Makefile (while attached to necessary compute resources, e.g., on a cluster) and then commit the executed `*.ipynb` (*with cell output*) into the repository. This means that when the sphinx build process runs on Github actions, it just uses `nbsphinx` to convert the pre-executed notebook to HTML, no access to computational resources needed. This has worked OK as a build loop so far, but the fact that some tutorials live outside of the CI loop causes some friction in the development workflow: rerunning a separate tutorial script on a local machine after each commit is difficult to remember, therefore there's a risk that the tutorial materials will become out of date and create a frustrating experience for new users.

**Describe the solution you'd like**
It would be ideal if all tutorial content (either in `*.py` or `*.ipynb` format) were tested as thoroughly and on the same schedule as the source package and built at the same time as the docs. Originally, I thought lumping the large-tutorials in with the ci-tutorials was impractical and would trigger runtime limits on Github actions. [Digging deeper](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions), it seems as though the runtime limits are quite substantial (6hrs per job, 72hrs per workflow) and it might be possible to set something up without worrying about hitting them. 

With some smart Github workflow configuration we can probably minimize the number of times the large tutorials need to be built. What if we added a test docs build as another job ontop of the tests? That way we could get quick confirmation whether the core tests ran, and could wait longer to see whether the docs also built correctly.

It would be nice if we could set up a better build/testing environment for the notebooks (locally), so that when we merge a feature branch to main, there is a very high probability that the docs will build with no errors, since the docs build job could take up to an hour or more. 

I think I've struggled defining what it means to "test" a notebook. Is a full end-to-end run with no errors a passing test? Do we need to construct assert statements on the output from individual cells? What functionality do the Jupyter notebooks test that isn't included in the Pytest `tests/` suite itself?

A set of actions that can help are:

- [x] extend the core Pytest suite to encompass as many use cases as possible, including "tutorial-specific" entities like tensorboard logging or Ray Tune hyperparameters. That way code in a tutorial notebook wouldn't be venturing into unexplored territory.
- [x] move large-tutorials and ci-tutorials back into `tutorials`
- [ ] create a branched build process for the docs (including tutorials)
   - [ ]  local builds take advantage of cluster resources and/or GPUs (e.g., `make html` is launched with cores available), so that docs build time is as short as possible during the development loop. We could even write a cluster submission script specifically for local docs build
   - [x] github actions builds run on single cores (core availability sensed in tutorial document itself), serially or parallelized across sets of jobs within the same docs workflow

**Describe alternatives you've considered**
We also tried exploring self-hosted github runners through our compute cluster, but it seems like these are ill-advised for public repositories.
