### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by iancze** [MPoL-dev/MPoL#5]
This issue aggregates issues planned for development.

# 0.1.0

## Code
- [x] `SimpleRMLNet` and precomposed models module
- [x]  Residual image class/tracker #6 
- [x] Gridder dirty image units in arcsec

## Doc
- [x] Optimization tutorial using ALMA Logo dataset

# 0.1.1

## Code
- [x] Dartboard iterator
- [x] Cross validation DatasetLoader

## Doc
- [x] Cross validation tutorial
- [ ] #27 CI for Jupyter notebooks + improved Github actions workflow
- [ ]  Option for running on GPU #28 
- [ ]  Real data tutorial on HD 143006 #25 
* JOSS submission

# 0.1.2

## Doc
* Cross validation with Tensorboard
* Using MPoL for model fitting with Pyro

**Comment by iancze** [comment]
Closing in favor of v0.1.1 milestone tracker
